print("this is the first code that is write to push on the repo")
print("it was not hard to setup the WSL to start the Gem5")
print("Trying to pushing on my repo Gem5")
print("awww baby you done your first commit")
print("testing with the commit")